title: "Rahul Sridhar"
email: "rahul.rsridhar@gmail.com"
baseurl: ""
url: "localhost:4000"
#url: "http://rahulsridhar.github.io/"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections: 
  projects:
    output: true

